name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_APP_X_KEY: ${{ secrets.VITE_APP_X_KEY }}
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      API_VERSION: ${{ secrets.VITE_API_VERSION }}

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: dist
