"""initial migration

Revision ID: bad60e1ea0b6
Revises: e129fdf26fe6
Create Date: 2025-09-20 11:55:05.959079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bad60e1ea0b6'
down_revision: Union[str, Sequence[str], None] = 'e129fdf26fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('notify_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_users_chat_id'), 'telegram_users', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_users_id'), 'telegram_users', ['id'], unique=False)
    op.drop_constraint(op.f('users_telegram_chat_id_key'), 'users', type_='unique')
    op.drop_column('users', 'notify_time')
    op.drop_column('users', 'telegram_chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_chat_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('notify_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_telegram_chat_id_key'), 'users', ['telegram_chat_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_telegram_users_id'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_chat_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
