name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio python-dotenv

      - name: Decrypt .env file
        run: ./decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Convert .env to Unix format
        run: sed -i 's/\r$//' $HOME/secrets/.env

      - name: Print one env var
        run: echo "Loaded SECRET_KEY=$FRONTEND_URL"

      - name: Load .env into environment
        run: |
          set -a
          source $HOME/secrets/.env
          set +a
          pytest -s -vv

      # Docker build and push only if tests pass

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=amenkhnissi/burgeramt-slot-finder
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=amenkhnissi/burgeramt-slot-finder
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
