name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

env:
  VITE_APP_X_KEY: ${{ secrets.VITE_APP_X_KEY }}
  VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
  API_VERSION: ${{ secrets.VITE_API_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist

  # Docker build and push only if tests pass

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=amenkhnissi/burgeramt-frontend
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=amenkhnissi/burgeramt-frontend
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
