name: Telegram Bot CI

on:
  push:
    paths:
      - "telegram_bot/**"
      - ".github/workflows/telegram_bot.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ${{ secrets.BACKEND_URL }}
      API_KEY: ${{ secrets.API_KEY }}
      API_VERSION: ${{ secrets.API_VERSION }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    defaults:
      run:
        working-directory: telegram_bot

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-asyncio python-dotenv

      - name: Run tests
        run: |
          python -m pytest -s -vv

      # Docker build and push only if tests pass

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: telegram_bot

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URI }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.AWS_ECR_URI }}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image to ECR
        run: |
          IMAGE_NAME=${{ secrets.AWS_ECR_URI }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      # Deploy to ECS only if Docker build and push succeed

  deploy:
    name: Deploy to AWS ECS
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition ${{ secrets.ECS_TASK_DEFINITION }} \
          --query 'taskDefinition.{family:family, taskRoleArn:taskRoleArn, executionRoleArn:executionRoleArn, networkMode:networkMode, containerDefinitions:containerDefinitions, volumes:volumes, placementConstraints:placementConstraints, requiresCompatibilities:requiresCompatibilities, cpu:cpu, memory:memory}' \
          --output json > task-definition.json

      - name: Clean task definition for re-registration
        run: |
          jq 'del(.taskRoleArn, .executionRoleArn) |
              del(.volumes, .placementConstraints) |
              del(.tags, .pidMode, .ipcMode, .proxyConfiguration, .inferenceAccelerators, .ephemeralStorage, .runtimePlatform, .enableFaultInjection)' \
              task-definition.json > cleaned-task-definition.json

      - name: Update image in task definition
        run: |
          IMAGE_URI=${{ secrets.AWS_ECR_URI }}:${{ github.sha }}
          jq --arg IMAGE_URI "$IMAGE_URI" \
            '.containerDefinitions[0].image = $IMAGE_URI' \
            task-definition.json > new-task-definition.json

      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json

      - name: Deploy updated task to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_SERVICE_NAME }} \
            --force-new-deployment
